;; ARQUIVO GERADO AUTOMATICAMENTE por gerador_problema.py
;; A ordem das paradas abaixo foi decidida pela camada geometrica.
;; Nao editar a mao: rode `python prototipo/orquestrador.py`.

(define (problem microarea-turno)
  (:domain visita-domiciliar-acs)

  (:objects
    acs1 - agente
    p1 p2 p3 p4 p5 p6 p7 p8 - paciente
    ubs ubs-fim casa-p1 casa-p2 casa-p3 casa-p4 casa-p5 casa-p6 casa-p7 casa-p8 - local
    n0 n1 n2 n3 n4 n5 n6 n7 n8 - nivel
  )

  (:init
    ;; posicao inicial e identificacao da unidade
    (em acs1 ubs)
    (e-ubs ubs)
    (e-ubs ubs-fim)   ; mesma UBS, papel de chegada/reposicao

    ;; ROTA FIXADA PELA CAMADA GEOMETRICA (vizinho mais proximo + 2-opt)
    ;; ubs -> p1 -> p7 -> p3 -> p2 -> p6 -> p4 -> p5 -> p8 -> ubs
    (proxima-parada ubs casa-p1)
    (proxima-parada casa-p1 casa-p7)
    (proxima-parada casa-p7 casa-p3)
    (proxima-parada casa-p3 casa-p2)
    (proxima-parada casa-p2 casa-p6)
    (proxima-parada casa-p6 casa-p4)
    (proxima-parada casa-p4 casa-p5)
    (proxima-parada casa-p5 casa-p8)
    (proxima-parada casa-p8 ubs-fim)

    ;; vinculo residencia <-> paciente e desvios possiveis ate a UBS
    (residencia-de p1 casa-p1)
    (desvio-ubs casa-p1 ubs-fim)
    (residencia-de p2 casa-p2)
    (desvio-ubs casa-p2 ubs-fim)
    (residencia-de p3 casa-p3)
    (desvio-ubs casa-p3 ubs-fim)
    (residencia-de p4 casa-p4)
    (desvio-ubs casa-p4 ubs-fim)
    (residencia-de p5 casa-p5)
    (desvio-ubs casa-p5 ubs-fim)
    (residencia-de p6 casa-p6)
    (desvio-ubs casa-p6 ubs-fim)
    (residencia-de p7 casa-p7)
    (desvio-ubs casa-p7 ubs-fim)
    (residencia-de p8 casa-p8)
    (desvio-ubs casa-p8 ubs-fim)

    ;; condicoes do caput do art. 3o par. 4o da Lei 11.350/2006
    ;; (curso-tecnico-concluido acs1)  <- AUSENTE de proposito
    (equipamento-disponivel acs1)

    ;; contador discreto de niveis (substitui fluentes numericos)
    (prox n0 n1)
    (prox n1 n2)
    (prox n2 n3)
    (prox n3 n4)
    (prox n4 n5)
    (prox n5 n6)
    (prox n6 n7)
    (prox n7 n8)
    (fitas n2)
    (nivel-maximo n2)
    (janelas n8)

    ;; necessidades clinicas: marca-se o que JA esta quitado.
    ;; a ausencia de (X-ok p) significa que o procedimento e exigido.
    (glicemia-ok p1)
    ;; p1: exige PA, vacinal (pessoa_idosa)
    (vacinal-ok p2)
    ;; p2: exige PA, glicemia (adulto)
    (glicemia-ok p3)
    ;; p3: exige PA, vacinal (gestante)
    (vacinal-ok p4)
    ;; p4: exige PA, glicemia (adulto)
    (pa-ok p5)
    (glicemia-ok p5)
    ;; p5: exige vacinal (crianca)
    (pa-ok p6)
    ;; p6: exige glicemia, vacinal (pessoa_idosa)
    (glicemia-ok p7)
    (vacinal-ok p7)
    ;; p7: exige PA (adulto)
    ;; p8: exige PA, glicemia, vacinal (pessoa_idosa)

    ;; custos em minutos, vindos da matriz de distancias (haversine)
    (= (total-cost) 0)
    (= (custo-deslocamento ubs casa-p1) 10)
    (= (custo-deslocamento ubs casa-p2) 11)
    (= (custo-deslocamento ubs casa-p3) 18)
    (= (custo-deslocamento ubs casa-p4) 12)
    (= (custo-deslocamento ubs casa-p5) 15)
    (= (custo-deslocamento ubs casa-p6) 15)
    (= (custo-deslocamento ubs casa-p7) 20)
    (= (custo-deslocamento ubs casa-p8) 16)
    (= (custo-deslocamento casa-p1 ubs) 10)
    (= (custo-deslocamento casa-p1 ubs-fim) 10)
    (= (custo-deslocamento casa-p1 casa-p2) 11)
    (= (custo-deslocamento casa-p1 casa-p3) 11)
    (= (custo-deslocamento casa-p1 casa-p4) 22)
    (= (custo-deslocamento casa-p1 casa-p5) 21)
    (= (custo-deslocamento casa-p1 casa-p6) 24)
    (= (custo-deslocamento casa-p1 casa-p7) 10)
    (= (custo-deslocamento casa-p1 casa-p8) 18)
    (= (custo-deslocamento casa-p2 ubs) 11)
    (= (custo-deslocamento casa-p2 ubs-fim) 11)
    (= (custo-deslocamento casa-p2 casa-p1) 11)
    (= (custo-deslocamento casa-p2 casa-p3) 9)
    (= (custo-deslocamento casa-p2 casa-p4) 19)
    (= (custo-deslocamento casa-p2 casa-p5) 26)
    (= (custo-deslocamento casa-p2 casa-p6) 16)
    (= (custo-deslocamento casa-p2 casa-p7) 18)
    (= (custo-deslocamento casa-p2 casa-p8) 26)
    (= (custo-deslocamento casa-p3 ubs) 18)
    (= (custo-deslocamento casa-p3 ubs-fim) 18)
    (= (custo-deslocamento casa-p3 casa-p1) 11)
    (= (custo-deslocamento casa-p3 casa-p2) 9)
    (= (custo-deslocamento casa-p3 casa-p4) 28)
    (= (custo-deslocamento casa-p3 casa-p5) 31)
    (= (custo-deslocamento casa-p3 casa-p6) 25)
    (= (custo-deslocamento casa-p3 casa-p7) 13)
    (= (custo-deslocamento casa-p3 casa-p8) 29)
    (= (custo-deslocamento casa-p4 ubs) 12)
    (= (custo-deslocamento casa-p4 ubs-fim) 12)
    (= (custo-deslocamento casa-p4 casa-p1) 22)
    (= (custo-deslocamento casa-p4 casa-p2) 19)
    (= (custo-deslocamento casa-p4 casa-p3) 28)
    (= (custo-deslocamento casa-p4 casa-p5) 16)
    (= (custo-deslocamento casa-p4 casa-p6) 11)
    (= (custo-deslocamento casa-p4 casa-p7) 32)
    (= (custo-deslocamento casa-p4 casa-p8) 21)
    (= (custo-deslocamento casa-p5 ubs) 15)
    (= (custo-deslocamento casa-p5 ubs-fim) 15)
    (= (custo-deslocamento casa-p5 casa-p1) 21)
    (= (custo-deslocamento casa-p5 casa-p2) 26)
    (= (custo-deslocamento casa-p5 casa-p3) 31)
    (= (custo-deslocamento casa-p5 casa-p4) 16)
    (= (custo-deslocamento casa-p5 casa-p6) 26)
    (= (custo-deslocamento casa-p5 casa-p7) 28)
    (= (custo-deslocamento casa-p5 casa-p8) 7)
    (= (custo-deslocamento casa-p6 ubs) 15)
    (= (custo-deslocamento casa-p6 ubs-fim) 15)
    (= (custo-deslocamento casa-p6 casa-p1) 24)
    (= (custo-deslocamento casa-p6 casa-p2) 16)
    (= (custo-deslocamento casa-p6 casa-p3) 25)
    (= (custo-deslocamento casa-p6 casa-p4) 11)
    (= (custo-deslocamento casa-p6 casa-p5) 26)
    (= (custo-deslocamento casa-p6 casa-p7) 33)
    (= (custo-deslocamento casa-p6 casa-p8) 30)
    (= (custo-deslocamento casa-p7 ubs) 20)
    (= (custo-deslocamento casa-p7 ubs-fim) 20)
    (= (custo-deslocamento casa-p7 casa-p1) 10)
    (= (custo-deslocamento casa-p7 casa-p2) 18)
    (= (custo-deslocamento casa-p7 casa-p3) 13)
    (= (custo-deslocamento casa-p7 casa-p4) 32)
    (= (custo-deslocamento casa-p7 casa-p5) 28)
    (= (custo-deslocamento casa-p7 casa-p6) 33)
    (= (custo-deslocamento casa-p7 casa-p8) 23)
    (= (custo-deslocamento casa-p8 ubs) 16)
    (= (custo-deslocamento casa-p8 ubs-fim) 16)
    (= (custo-deslocamento casa-p8 casa-p1) 18)
    (= (custo-deslocamento casa-p8 casa-p2) 26)
    (= (custo-deslocamento casa-p8 casa-p3) 29)
    (= (custo-deslocamento casa-p8 casa-p4) 21)
    (= (custo-deslocamento casa-p8 casa-p5) 7)
    (= (custo-deslocamento casa-p8 casa-p6) 30)
    (= (custo-deslocamento casa-p8 casa-p7) 23)
    (= (custo-desvio casa-p1) 20)
    (= (custo-desvio casa-p2) 22)
    (= (custo-desvio casa-p3) 36)
    (= (custo-desvio casa-p4) 24)
    (= (custo-desvio casa-p5) 30)
    (= (custo-desvio casa-p6) 30)
    (= (custo-desvio casa-p7) 40)
    (= (custo-desvio casa-p8) 32)
  )

  ;; Todo paciente da lista precisa ter o protocolo integralmente
  ;; cumprido, e o agente precisa terminar o turno de volta na UBS.
  (:goal (and
    (protocolo-cumprido p1)
    (protocolo-cumprido p2)
    (protocolo-cumprido p3)
    (protocolo-cumprido p4)
    (protocolo-cumprido p5)
    (protocolo-cumprido p6)
    (protocolo-cumprido p7)
    (protocolo-cumprido p8)
    (em acs1 ubs-fim)
  ))

  (:metric minimize (total-cost))
)
